/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jflei_fskube_FSKubeWrapper */

#ifndef _Included_com_jflei_fskube_FSKubeWrapper
#define _Included_com_jflei_fskube_FSKubeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jflei_fskube_FSKubeWrapper
 * Method:    initialize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jflei_fskube_FSKubeWrapper_initialize
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_jflei_fskube_FSKubeWrapper
 * Method:    addSample
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jflei_fskube_FSKubeWrapper_addSample
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_jflei_fskube_FSKubeWrapper
 * Method:    getTimeMillis
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jflei_fskube_FSKubeWrapper_getTimeMillis
  (JNIEnv *, jclass);

/*
 * Class:     com_jflei_fskube_FSKubeWrapper
 * Method:    getLogLevels
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jflei_fskube_FSKubeWrapper_getLogLevels
  (JNIEnv *, jclass);

/*
 * Class:     com_jflei_fskube_FSKubeWrapper
 * Method:    setLogLevels
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jflei_fskube_FSKubeWrapper_setLogLevels
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
