language: cpp

before_install:
    - sudo apt-get -qq install swig python3-dev

script:
    - make
    - make py
    - make check

compiler:
    - clang

# Have to whitelist gh-pages.
# http://docs.travis-ci.com/user/build-configuration/#White--or-blacklisting-branches
branches:
    only:
        - gh-pages
