BLD := bld
SRC := src
RELEASE := release
CXX := clang++
CFLAGS := -Wall -g -std=c++11 -Wno-c++11-narrowing 
INC := -I/usr/include/python3.3m -I/usr/include/python3.2 -I$(SRC)

CLOJURE_COMPILER := java -jar ~/thirdrepos/cc/compiler.jar 

PYTHONWRAPPER_OBJS := $(BLD)/fskube.o $(BLD)/fskube_wrap.o $(BLD)/logging.o

# Create BLD and RELEASE directory if necessary
$(shell mkdir -p $(BLD) $(RELEASE))

.PHONY: all py js jsmin check clean serve release

default: $(BLD)/fskube.o
        
all: default py js jsmin

release: $(RELEASE)/fskube.js

py: $(BLD)/_fskube.so

js: $(BLD)/fskube.js

jsmin: $(BLD)/fskube.min.js

# Autogenerated dependencies trick from
# http://scottmcpeak.com/autodepend/autodepend.html
-include $(PYTHONWRAPPER_OBJS:.o=.d)

$(BLD)/_fskube.so: $(PYTHONWRAPPER_OBJS)
	$(CXX) -shared $(CFLAGS) $(INC) $^ -o $@

$(RELEASE)/fskube.js: $(BLD)/fskube.js
	cp $^ $@

# Since some cpp files are autogenerated and end up in the BLD directory,
# treat all cpp files as being in the bld directory. This is a simple rule
# to copy those cpp files that are not actually autogenerated.
$(BLD)/%.cpp: $(SRC)/%.cpp
	cp $< $@

# Make recognizes that the cpp files we copied into BLD are "intermediate" files,
# and will kindly automatically delete them after compilation. However, the
# dependency information generated by CXX points at these BLD files.
# http://www.gnu.org/software/make/manual/html_node/Chained-Rules.html
# details this trick to prevent the deletion of "intermediate" files.
.PRECIOUS: $(BLD)/%.cpp

$(BLD)/%.o: $(BLD)/%.cpp
	$(CXX) -c -fPIC $(CFLAGS) $(INC) $< -o $@
	$(CXX) -MM -MT $(BLD)/$*.o $(CFLAGS) $(INC) $< > $(BLD)/$*.d

# These targets don't actually depend on fskube.o, but they
# should get remade whenever fskube.o is remade, so it's listed
# as a dependency.
$(BLD)/fskube.py $(BLD)/fskube_wrap.cpp $(BLD)/fskube_wrap.h: $(BLD)/fskube.o $(SRC)/fskube.i
	swig -builtin -python -c++ -o $(BLD)/fskube_wrap.cpp $(SRC)/fskube.i

# Similar trick as above: fskube.js doesn't actually depend on
# fskube.o/logging.o, but every time fskube.o/logging.o gets remade,
# fskube.js should be remade as well.
$(BLD)/fskube.js: $(BLD)/fskube.o $(BLD)/logging.o $(SRC)/embind.cpp
	em++ $(CFLAGS) --bind $(SRC)/embind.cpp $(SRC)/fskube.cpp $(SRC)/logging.cpp -o $@

$(BLD)/fskube.min.js: $(BLD)/fskube.js
	$(CLOJURE_COMPILER) $^ --language_in ECMASCRIPT5 > $@

check: py
	PYTHONPATH=$(BLD) python3 -m unittest discover -s test/ -p *Test.py

clean:
	rm -rf $(BLD)

serve: release
	python -m SimpleHTTPServer
